blank_issues_enabled: true
contact_links:
  - name: â“ Ask a Question
    url: https://github.com/ConduitIO/conduit/discussions
    about: Please ask and answer questions here.
  - name: ğŸ“„ Documentation Issue
    url: https://github.com/ConduitIO/conduit-site
    about: Please report issues regarding documentation here.
  - name: ğŸ’¬ Chat with us
    url: https://discord.com/channels/828680256877363200/933725823813451797
    about: Join our Discord server to chat with us.
